---
kind: pipeline
type: docker

platform:
  os: linux
  arch: amd64

steps:
- name: docker
  image: plugins/docker
  settings:
    context: ./app-2
    dockerfile: ./app-2/Dockerfile
    auto_tag: true
    password: "${harbor_password}"
    repo: harbor.amazingdesign.eu/sandbox/app-2
    username: "${harbor_username}"

trigger:
  branch:
  - master
  event:
  - tag

...
