stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: chomamateusz/sandbox/docker-node-example
      pushRemote: true
      registry: index.docker.io
timeout: 60
notification: {}
